trigger:
  branches:
    include:
      - main
      - dev
pr:
  drafts: false
  branches:
    include:
      - dev
      - main
      - feature/*
      - fix/*
resources:
  repositories:
    - repository: templates
      type: github
      name: saikumar1207-p/dso_azure_pipeline_templates
      ref: main
      endpoint: saikumar1207-p
stages:
  - stage: CodeQuality
    displayName: Code Quality Checks    
    jobs:
    - job:
      steps:
       - task: UsePythonVersion@0
         inputs:
              versionSpec: '3.12'
              addToPath: true
       - script: |
          echo "hi"  
         
         
