trigger:
  branches:
    include:
      - main
      - dev

pr:
  drafts: false
  branches:
    include:
      - main
      - dev
      - feature/*
      - fix/*

resources:
  repositories:
    - repository: templates
      type: github
      name: saikumar1207-p/dso_azure_pipeline_templates
      ref: refs/heads/main    # ✅ Recommended explicit format
      endpoint: saikumar1207-A

stages:
  - stage: CodeQuality
    displayName: Code Quality Checks
    jobs:
      - job: CodeQualityJob
        displayName: Run Code Quality Job
        steps:
          - checkout: self
          - script: echo "Running code quality checks..."
            displayName: Echo Message
