resources:
  pipelines:
    - pipeline: mainpipe
      source: mainpipeline
      trigger: true

trigger:
  branches:
    include:
      - main
      - dev
      - feature/*

pool:
  name: 'default'

steps:
- script: echo "Pipeline B triggered after Pipeline A finished"
