resources:
  pipelines:
    - pipeline: mainpipe
      source: mainpipeline
      trigger: true

trigger: none

pool:
  name: 'default'

steps:
- script: echo "Pipeline B triggered after Pipeline A finished"
